/*
 * gRPC server node to accept calls from the clients and serve based on the method that has been requested
 */

package io.grpc.filesystem.task3;

import com.task3.proto.AssignJobGrpc;
import io.grpc.Server;
import io.grpc.ServerBuilder;
import io.grpc.filesystem.task2.MapReduce;
import com.task3.proto.AssignJobGrpc;
import com.task3.proto.MapInput;
import com.task3.proto.MapOutput;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import io.grpc.stub.StreamObserver;

import java.io.IOException;
import java.util.concurrent.TimeUnit;

public class MrMapServer {

    private Server server;

    public static void main(String[] args) throws IOException, InterruptedException {
        final MrMapServer mrServer = new MrMapServer();
        for (String i : args) {
            mrServer.start(Integer.parseInt(i));
        }
        mrServer.server.awaitTermination();
    }

    private void start(int port) throws IOException {
        server = ServerBuilder.forPort(port).addService(new MrMapServerImpl()).build().start();
        System.out.println("Listening on: " + port);
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            System.err.println("Terminating the server at port: " + port);
            try {
                server.shutdown().awaitTermination(10, TimeUnit.SECONDS);
            } catch (InterruptedException e) {
                e.printStackTrace(System.err);
            }
        }));
    }

    static class MrMapServerImpl extends AssignJobGrpc.AssignJobImplBase {

        /*
         * Insert your code here.
         * Override the map function to accept the request and perform Map
         * Understand the autogenerated file Assignment1/BCS-DS-Assignment-Package/Task3/app/build/generated/source/proto/main/grpc/com/task3/proto/AssignJobGrpc.java
         * Look through the available functions and definition in this Grpc file to complete the task
         * Use your previously written MapReduce.map function.
         */
        @Override
        public StreamObserver<MapInput> map(StreamObserver<MapOutput> responseObserver) {
            System.out.println("Map request received");

            return new StreamObserver<MapInput>() {

                @Override
                public void onNext(MapInput request) {
                    String inputFilePath = request.getInputfilepath();
                    try {
                        // Use the MapReduce.map function to process the input file
                        MapReduce.map(inputFilePath);
                        // Optionally, you can handle outputFilePath if needed
                    } catch (IOException e) {
                        // Send an error to the client if mapping fails
                        responseObserver.onError(e);
                    }
                }

                @Override
                public void onError(Throwable t) {
                    // Handle any errors from the client
                    responseObserver.onError(t);
                }

                @Override
                public void onCompleted() {
                    // After all MapInput messages are processed, send a MapOutput response
                    MapOutput response = MapOutput.newBuilder().setJobstatus(2).build(); // Assuming 2 indicates success
                    responseObserver.onNext(response);
                    responseObserver.onCompleted();
                    System.out.println("Map request processed succesfully!\n");

                }
            };
        }
    }
}
